language: c
sudo: required
services:
  - redis-server
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
cache:
    directories:
    - $HOME/.opam
env:
  global:
    - PACKAGE=orewa
    - TESTS=true
    - POST_INSTALL_HOOK="opam reinstall --with-test orewa && make integration"
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09 EXTRA_DEPS="ocamlformat.0.12" PRE_INSTALL_HOOK="make format"
