language: c
sudo: required
services:
  - redis-server
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=orewa
    - TESTS=true
    - POST_INSTALL_HOOK="opam install ocamlformat>=0.9 && make format && opam install alcotest alcotest-async && make integration"
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
